In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('C:/Users/prash/Desktop/python materials/python_data_projects/project_IPL_analysis/delivery.csv')
df_matches=pd.read_csv('C:/Users/prash/Desktop/python materials/python_data_projects/project_IPL_analysis/matches.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [4]:
df.sample(10)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
111206,829723,2,Kolkata Knight Riders,Chennai Super Kings,4,4,RV Uthappa,MM Sharma,MK Pandey,0,0,0,NaN,0,NaN,NaN,NaN
96860,729297,2,Rajasthan Royals,Chennai Super Kings,5,6,SV Samson,R Ashwin,SR Watson,0,0,0,NaN,0,NaN,NaN,NaN
34779,419137,2,Rajasthan Royals,Chennai Super Kings,3,3,MJ Lumb,DE Bollinger,NV Ojha,0,4,4,byes,0,NaN,NaN,NaN
73208,548368,2,Chennai Super Kings,Kolkata Knight Riders,16,5,F du Plessis,SP Narine,MS Dhoni,0,0,0,NaN,0,NaN,NaN,NaN
118639,829789,2,Mumbai Indians,Chennai Super Kings,1,2,PA Patel,MM Sharma,LMP Simmons,4,0,4,NaN,0,NaN,NaN,NaN
166964,1175365,1,Kolkata Knight Riders,Delhi Capitals,5,3,CA Lynn,HV Patel,RV Uthappa,0,0,0,NaN,0,NaN,NaN,NaN
112660,829735,2,Rajasthan Royals,Chennai Super Kings,3,4,AM Rahane,MM Sharma,SR Watson,1,0,1,NaN,0,NaN,NaN,NaN
234233,1359508,2,Sunrisers Hyderabad,Delhi Capitals,14,4,H Klaasen,AR Patel,Washington Sundar,1,0,1,NaN,0,NaN,NaN,NaN
44593,501210,2,Kochi Tuskers Kerala,Mumbai Indians,4,2,DPMD Jayawardene,AG Murtaza,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN
254666,1426283,1,Gujarat Titans,Royal Challengers Bengaluru,15,4,DA Miller,GJ Maxwell,B Sai Sudharsan,1,0,1,NaN,0,NaN,NaN,NaN

We'll work on following analysis:

1. Best Batsman
- most runs
- best average
- best strike rate
- An ideal IPL batter: best strike rate + average > 170 and total runs over 2500
- batter with most 4s and 6s
- The Ideal IPL batter's runs opponent wise
- Box plot of runs scored by top run scorer(Virat Kohli) against opponents

2. Best Bowler
- bowlers with best strike rates
- bowlers with their bunnies
- bowlers with best average
- bowlers with best economy in death over
- bowler with most wickets

3. Matches
- Team wise IPL trophies
- Number of Finals won chasing or batting first?
- Teams who reached most times in qualifier round
- Chokers: reached qualifiers n times, but not won or won minimal trophies yet
- venue wise win percentage on bat first or field first